# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishBeltApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='wished_by',
            field=models.ManyToManyField(default='', related_name='wished_item', to='wishBeltApp.User'),
        ),
    ]
