# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishBeltApp', '0002_auto_20171026_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
